apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: mvnjunit-run-
spec:
  pipelineRef:
    name: maven-build
  resources:
  - name: app-git
    resourceSpec:
      type: git
      params:
        - name: url
          # value: https://github.com/spring-projects/spring-petclinic
          # value: https://github.com/LableOrg/java-maven-junit-helloworld
          value: https://hergi2004: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@github.com/hergi2004/Tekton-MVN-Junit.git
  workspaces:
  - name: local-maven-repo
    persistentVolumeClaim:
      claimName: maven-repo-pvc
