apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-repo-pvc
  # namespace: tekton
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
